Nosmoht/ansible-module-foreman

- foreman_operatingsystem.py
Maybe it's me not getting something but
with dict of operatingsystems like
```
foreman_operatingsystems:
- name: CentOS
family: 'Redhat'
major: 6
minor: 7
architectures:
- x86_64
media:
- CentOS local
ptables:
- vm lvm
state: present
- name: CentOS
family: 'Redhat'
major: 7
minor: 1.1503
architectures:
- x86_64
media:
- CentOS local
ptables:
- vm lvm
state: present
```
ansible fails with
```
TASK: [nosmoht.foreman | Ensure Operatingsystem] ****************************** 
failed: [foreman.infra.sbx.avp.ru] => (item={'major': 6, 'name': 'CentOS', 'family': 'Redhat', 'media': ['CentOS local'], 'ptables': ['vm lvm'], 'state': 'present', 'architectures': ['x86_64'], 'minor': 7}) => {"failed": true, "item": {"architectures": ["x86_64"], "family": "Redhat", "major": 6, "media": ["CentOS local"], …
```
> Fix rendering of multiple OS

- foreman_medium.py
- foreman_ptable.py
Add ability to specify os_family for medias
> Add os_family

- foreman_hostgroup.py
copied over from the host parameter code.
This needs https://github.com/Nosmoht/python-foreman/pull/13
> Allow to add hostgroup parameters

- foreman_compute_attribute.py
python-foreman wraps the vm_attributes in
{ 'vm_attrs': data }
so don't do it here since we don't correctly update the attributes
otherwise.
> Properly pass vm_attributes

- foreman_hostgroup.py
Foreman divides hostgroups from parent hostgroups by a '/' in the title,
e.g.
foo/green
webtier/green
dbtier/green
secure/webtier/green
while the name of the hostgroup would always be "green".
So in order to not pick a hostgroup at random search by title and if the
hostgroup name contains slashes wire up the correct parent host group so
we inherit it's parameters.
This also includes the changes from 
https://github.com/Nosmoht/ansible-module-foreman/pull/15
since they overlap.
> Hostgroup parents

- foreman_config_template.py
The REST API requires an id and bails out on the template name.
(as seen with foreman 1.10.1)
This needs https://github.com/Nosmoht/python-foreman/pull/12
> Resolve template_kind_name to an id

- foreman_operatingsystem.py
They're not needed with image based installs
> Don't require OS to have media and ptables

- foreman_config_template.py
If we only search for the name we fail when we have e.g. several Debian
version like:
"Debian 7.9"
"Debian 8.3"
"SLES 12.0"
since the query then returns multiple results. Because Foreman nicely
builds the title out of the name, os_major and os_minor search for that
instead.
> Search for title instead of just name

- foreman_subnet.py
I use boot_mode Static for my Foreman instances.
With this PR I am able to set it as I want
> Add boot_mode argument to foreman_subnet

- foreman_compute_attribute.py
otherwise we fail if we don't set foreman_ssl attribute.
> foreman_compute_attribute: Set default for ssl

- foreman_host.py
If no hostgroups are found, search by title to be able to specify the
full name of nested hostgroups.
> host: search hostgroup by title

- foreman_host.py
The return values for the power_action "state" come from the BMC or
hypervisor Foreman makes the calls to, so they aren't unified.
On vSphere the return values seem to be on and off, so check the power
state against these values as well.
> host: also check for power state on and off

- foreman_subnet.py
Change a61f59e4fb7ab7a1c5f2223ea482e9ee25eba9e0 broke subnets without a
boot_mode like:
"Could not update subnet: Boot mode is not included in the list"
> ansible-foreman-module: set default boot mode

- foreman_architecture.py
- foreman_compute_attribute.py
- foreman_compute_profile.py
- foreman_compute_resource.py
- foreman_config_template.py
- foreman_domain.py
- foreman_environment.py
- foreman_host.py
- foreman_image.py
- foreman_ldap.py
- foreman_location.py
- foreman_medium.py
- foreman_operatingsystem.py
- foreman_organization.py
- foreman_os_default_template.py
- foreman_ptable.py
- foreman_realm.py
- foreman_role.py
- foreman_smart_proxy.py
- foreman_subnet.py
- foreman_user.py
Ansible wants
from ansible.module_utils.basic import *
otherwise it aborts with:
fatal: [foo.example.com]: FAILED! => {"failed": true, "msg": "ERROR! error importing module in /home/godiug/infra20/ansible-foreman-resources/library/ansible-module-foreman/foreman_image.py, expecting format like 'from ansible.module_utils.basic import *'"}
on Ansible 2.0 at least.
See
http://docs.ansible.com/ansible/dev_guide/developing_program_flow_modules.html#module-replacer
for details.
> Fix imports

- foreman_medium.py
Adding a code-block to foreman_medium.py to be able to clean all existing media from a foreman-environment.
The cleaning can be achieved by choosing '*' as the medium name and state 'absent'
> Clean all media feature

- foreman_compute_attribute.py
so far we printed the compute resource name but we should print the
profile name. Otherwise it's hard to find out what exactly failed.
> compute_resource_attribute: fix error message

- foreman_operatingsystem.py
otherwise we might end up with multiple matches for e.g. Debian 8.0 and
8.1
> operatingsystem: look for os minor version as well

- foreman_hostgroup.py
Fix a variable name and don't log root password (although it's usually encrypted it's better to not log it and it silences a ansible warning)
> Hostgroup fixes

- foreman_config_template.py
otherwisw e.g. SLES 12.0 and SLES 12.1 aren't distinguishable
> config_template: search for title instead of name

- foreman_config_template.py
This will prevent us from updating the template_kind but otherwise we
fail every update with:
fatal: [foo -> localhost]: FAILED! =>
{"changed": false, "failed": true, "msg": "Could not update config
template: PG::UndefinedFunction: ERROR:  operator does not exist:
character varying = integer\nLINE 1: ...mplate_kinds\".\"id\" = 5 OR
\"template_kinds\".\"name\" = 5)) ORDE...\n ^\nHINT:  No operator
matches the given name and argument type(s). You might need to add
explicit type casts.\n: SELECT \"template_kinds\".* FROM
\"template_kinds\"  WHERE ((\"template_kinds\".\"id\" = 5 OR
\"template_kinds\".\"name\" = 5)) ORDER BY CASE WHEN
\"template_kinds\".\"name\" = 5 THEN 1 ELSE 0 END LIMIT 1"}
this is a foreman bug in the end but otherwise updates break completely
over here.
Might be debatable …
> config_template: drop template_kind_id on updates

- foreman_user.py
Without this newer foreman will fail since it has a non-null constraint
on the admin column.
> Set a proper default for admin

- module_utils/foreman_utils.py
This addresses an idempotency bug in the config templates module caused by incorrect variables being referenced in this function.
> Fixed bug in module_utils/foreman_utils.py

- foreman_host.py
With the current code, for a baremetal host not controlled via BMC,
even when state is simply "present" or "absent", the ansible-module-foreman
code will try to retrieve power information from foreman, which will
fail ("Power operations are not enabled on this host."").
With this error will only appear in the relevant cases: the cases
where state was set to 'rebooted','running' or 'stopped'.
> host: do not try to retrieve host power status if not needed

- foreman_host.py
Had an issue when using ```state: running``` that the script did not power on my virtual machine.
> Fix for power on when state is running and host doesn't exist

- foreman_config_template.py
- module_utils/foreman_utils.py
'title' field (composite of name, major and minor ver) uniquely identifies Operating Systems. Use it in get_operatingsystem_ids.
Fix config templates 'operatingsystems' updates (similar to organizations and locations - need to send 'operatingsystem_ids' to Foreman).
Rework equality check of config template operating systems to only compare and trigger update if provided (otherwise existing template operating systems deleted when not provided in playbook).
> Templates operatingsystems update fix

- foreman_host.py
Added support for specifying the kickstart_repository_id. 
Als the content_source_id should be specified inside the content_facet attributes.
> add kickstart_repository_id and fix content_source_id location
