foreman_ldap.py
This needs https://github.com/Nosmoht/python-foreman/pull/14
=> Allow to configure ldap authentication sources sources

foreman_image.py
Fixes output errors in the error case and allows to set the image password (which was not obvious from the API docs)
=> Image password

foreman_architecture.py, foreman_compute_attribute.py, foreman_compute_profile.py, foreman_compute_resource.py, foreman_config_template.py, foreman_domain.py, foreman_environment.py, foreman_host.py, foreman_hostgroup.py, foreman_image.py, foreman_ldap.py, foreman_location.py, foreman_medium.py, foreman_operatingsystem.py, foreman_organization.py, foreman_os_default_template.py, foreman_ptable.py, foreman_role.py, foreman_smart_proxy.py, foreman_subnet.py, foreman_user.py
Don't put passwords into ansible output.
=> No log password

foreman_host.py
This solves the UnboundLocalError reported in #38.
=> host: set power_management_enabled when get_host_power succeeds

foreman_compute_resource.py
Based on https://github.com/Nosmoht/ansible-module-foreman/pull/47 this ignores the password on resource updates so we don't get idempotency.
See http://projects.theforeman.org/issues/17449
=> Skip password

foreman_filter.py
Allows to configure permission filters that are attached to roles
=> Allow to onfigure filters

foreman_external_usergroup.py
Needs https://github.com/Nosmoht/python-foreman/pull/31
=> Manage external usergroups

foreman_setting.py
Fixes a bug when remote value in Foreman is None and adds check_mode for the settings plugin (we have to start somewhere).
=> Settings check mode

foreman_host.py
Fixes #62. Underlying foreman python module needs to be updated as well. See PR https://github.com/Nosmoht/python-foreman/pull/33 for that.
=> Add support for updating a host

foreman_host.py
Added support for ip, interface_attributes and compute_attributes to foreman_host.py. This makes it possible to specify cpu, memory and network interface properties like name, type and network when creating a VM, and override what's specified by default in the template. Without it a template would be required for every desired configuration of cpu/mem/cores/netwerk/etc.
=> added ip, interface_attributes and compute_attributes support

foreman_global_parameter.py
Module manages foreman global parameters (formerly known as common parameters)
=> ADD foreman_global_parameter module

README.md, foreman_config_template.py, module_utils/foreman_utils.py
I have added support for locations and organizations in foreman_config_template.
I am planning to extend other resources as well, so i have moved common code into module_utils directory, since some of the organization/location code can be shared.
=> Config template org loc upd

foreman_host.py
Added support to define a realm for a host.
=> added realm support

foreman_config_template.py, foreman_global_parameter.py, foreman_ldap.py, foreman_medium.py, foreman_ptable.py, module_utils/foreman_utils.py
* Added organization and location support for medium, ptable, ldapp
* Added common funciton init_foreman_client to remove code duplications (I will continu to propagate it to other modules)
* Extended LDAP parameters
=> Medium ptable ldap upd

foreman_host.py
* changed comparison algorithm - now it only checks if only declared atributes match, this allows partial update of the existing host resource
* removed duplicities
* host is deleted earlier in the code when resource is set 'absent', no need to load aditional details about host
* refactored a bit to satisfy linter
* matched parameters in ensure with module names - it is not a good idea to use constacts from different lib here
=> REFACTOR foreman_host

foreman_config_template.py
* update template comparison to check only parameters defined in ansible with existing resource
* this allows for example to only change organizations on existing templates without changing template
* useful for adding and removing default templates from organizations
* add more dependency on foreman_utils
* sets locked default to False (Default fm server handling), and snippet to False - default as well
=> UPD foreman_config_template: equality check rework

foreman_ptable.py, module_utils/foreman_utils.py
Allow assignment of operating systems to ptables via ptables resource
=> Add operating system mgmt to ptables

foreman_hostgroup.py, foreman_medium.py, foreman_ptable.py
Similar to config_templates equality check rework (to only compare parameters defined) also implement in - foreman_hostgroup, foreman_medium, foreman_ptable.
=> Equality check rework.

foreman_smart_proxy.py
* Add handling for organizations and locations
* use `foreman_utils`
=> UPD foreman_smart_proxy

foreman_subnet.py
* fix missing smart proxy comparison
* allow configuring empty (tftp, dhcp, dns, discovery)_proxy
* refactor `subnets_equal` to contain `comparable_keys`
* allow configuration of discovery proxy (when using foreman discovery plugin)
=> UPD foreman_subnet: fix and extend subnet proxy config
